version: '2'

services:
    yin-middleware-php:
        container_name: yin-middleware-php
        image: php:8.0-cli
        volumes:
            - .:/var/www
        command: /bin/sh -c "cd /var/www; php vendor/bin/phpunit"
